name: Azure VM Connection

on:
  push:
    branches:
      - dev

jobs:
  connect-to-azure-vm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set variables
      run: |
        echo "VM_NAME=windows" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=Resourcegroup-test" >> $GITHUB_ENV
        echo "BASTION_HOST=windows-vnet-bastion" >> $GITHUB_ENV
        echo "USERNAME=karthik" >> $GITHUB_ENV
        echo "PASSWORD=${{ secrets.BASTION_PASSWORD }}" >> $GITHUB_ENV # Store the password securely in GitHub Secrets

    - name: Check VM Connectivity and Execute Commands
      id: run_script
      run: |
        # Check if the VM is running
        az vm get-instance-view --resource-group $RESOURCE_GROUP --name $VM_NAME --query "powerState" -o tsv
        
        # Run commands to change directory, list files, and run the echo.sh script
        output=$(az vm run-command invoke \
          --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --command-id RunPowerShellScript \
          --scripts "Start-Process 'C:\\Program Files\\Git\\bin\\bash.exe' -ArgumentList '-c', 'cd /c/Users/karthik; ls; ./echo.sh; echo \"This is a new file\" > karthik.txt' -Wait" \
          --query "value[0].message" -o tsv)

        echo "Output from commands: $output"

    - name: Display output
      run: echo "Output from commands: ${{ steps.run_script.outputs.output }}"
